### ISSUE TITLE
Update fails on http://p2-dev.pdt-extensions.org/ for PDT Extensions

### ISSUE THREAD

**Issue by raiserle** [pdt-eg/p2-mirror-dev#18]
An error occurred while collecting items to be installed
session context was:(profile=epp.package.java, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
Artifact not found: http://dl.bintray.com/pulse00/pdt-extensions/nightly/0.0.6/plugins/org.pdtextensions.core_0.22.2.201701260348.jar.
http://dl.bintray.com/pulse00/pdt-extensions/nightly/0.0.6/plugins/org.pdtextensions.core_0.22.2.201701260348.jar
Artifact not found: http://dl.bintray.com/pulse00/pdt-extensions/nightly/0.0.6/plugins/org.pdtextensions.core.ui_0.22.2.201701260348.jar.
http://dl.bintray.com/pulse00/pdt-extensions/nightly/0.0.6/plugins/org.pdtextensions.core.ui_0.22.2.201701260348.jar
Artifact not found: http://dl.bintray.com/pulse00/pdt-extensions/nightly/0.0.6/plugins/org.pdtextensions.repos_0.22.2.201701260348.jar.
http://dl.bintray.com/pulse00/pdt-extensions/nightly/0.0.6/plugins/org.pdtextensions.repos_0.22.2.201701260348.jar
Artifact not found: http://dl.bintray.com/pulse00/pdt-extensions/nightly/0.0.6/plugins/org.pdtextensions.repos.ui_0.22.2.201701260348.jar.
http://dl.bintray.com/pulse00/pdt-extensions/nightly/0.0.6/plugins/org.pdtextensions.repos.ui_0.22.2.201701260348.jar
Artifact not found: http://dl.bintray.com/pulse00/pdt-extensions/nightly/0.0.6/plugins/org.pdtextensions.semanticanalysis_0.22.2.201701260348.jar.
http://dl.bintray.com/pulse00/pdt-extensions/nightly/0.0.6/plugins/org.pdtextensions.semanticanalysis_0.22.2.201701260348.jar
Artifact not found: http://dl.bintray.com/pulse00/pdt-extensions/nightly/0.0.6/plugins/org.pdtextensions.semanticanalysis.ui_0.22.2.201701260348.jar.
http://dl.bintray.com/pulse00/pdt-extensions/nightly/0.0.6/plugins/org.pdtextensions.semanticanalysis.ui_0.22.2.201701260348.jar
Artifact not found: http://dl.bintray.com/pulse00/pdt-extensions/nightly/0.0.6/plugins/org.pdtextensions.server_0.22.2.201701260348.jar.
http://dl.bintray.com/pulse00/pdt-extensions/nightly/0.0.6/plugins/org.pdtextensions.server_0.22.2.201701260348.jar
Artifact not found: http://dl.bintray.com/pulse00/pdt-extensions/nightly/0.0.6/plugins/org.pdtextensions.server.ui_0.22.2.201701260348.jar.
http://dl.bintray.com/pulse00/pdt-extensions/nightly/0.0.6/plugins/org.pdtextensions.server.ui_0.22.2.201701260348.jar
Artifact not found: http://dl.bintray.com/pulse00/pdt-extensions/nightly/0.0.6/features/org.pdtextensions.feature_0.22.2.201701260348.jar.
http://dl.bintray.com/pulse00/pdt-extensions/nightly/0.0.6/features/org.pdtextensions.feature_0.22.2.201701260348.jar

**Comment by zulus** [comment]
fix in progress...

**Comment by zulus** [comment]
Fixed! You might need restart eclipse.

**Comment by raiserle** [comment]
Thank you. Works perfect!
