### ISSUE TITLE
Symfony Plugin 1.6.0 not available?

### ISSUE THREAD

**Issue by olberger** [pdt-eg/p2-mirror-dev#21]
I tried to install the Symfony plugin from the marketplace for 2021-06, which, I think, points to this pd-textensions.org repo, but it seems to be broken.

See also https://github.com/pulse00/Symfony-2-Eclipse-Plugin/issues/268

Am I wrong ? Maybe something that's indeed on the plugin's side...

Thanks in advance.

**Comment by Arckame** [comment]
Same issue.
Waiting for this plugin to come back.

**Comment by paulvi** [comment]
https://github.com/pdt-eg/p2-mirror-dev/blob/gh-pages/compositeContent.xml#L9

This repo is hosted on Bintray, that was shut down,
so magic will happen, unless someone will deploy to new location.

**Comment by zulus** [comment]
Fixed
